// Module to control the application lifecycle and the native browser window.
const { app, BrowserWindow } = require('electron');
const url = require('url');
const path = require('path');
const log = require('electron-log');

log.catchErrors();

// Create the native browser window.
function createWindow() {
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
  });

  // In production, set the initial browser path to the local bundle generated by webpack.
  // In development, set it to localhost to allow live/hot-reloading.
  const appURL = app.isPackaged
    ? url.format({
        pathname: path.join(__dirname, '..', 'dist', './index.html'),
        protocol: 'file:',
        slashes: true,
      })
    : 'http://localhost:8080';

  log.info(`About to launch app from URL: ${appURL}`);

  mainWindow.loadURL(appURL).then(() => {
    log.info('Renderer loaded successfully');
  });

  // Automatically open Chrome's DevTools in development mode.
  if (!app.isPackaged) {
    mainWindow.webContents.openDevTools();
  }
}

// This method will be called when Electron has finished its initialization and
// is ready to create the browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(() => {
  createWindow();

  app.on('activate', function () {
    // On macOS it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) {
      createWindow();
    }
  });
});

// Quit when all windows are closed, except on macOS.
// There, it's common for applications and their menu bar to stay active until
// the user quits  explicitly with Cmd + Q.
app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});
